### ISSUE TITLE
How did you compile closed captions file into .dat?

### ISSUE THREAD

**Issue by Blueberryy** [AwfulRanger/closecaption_english#1]
Hi i have issue when i drag and drop my txt file on captioncompiler.exe it just gives an error "captioncompiler.exe isn't working"

**Comment by Blueberryy** [comment]
I'm working on Russian localization for your closed captions

**Comment by AwfulRanger** [comment]
The caption compiler expects to be ran from a folder with gameinfo.txt, and the closecaption file to be in the resource folder.

Put your txt file into `Team Fortress 2/tf/resource`, then open a command prompt in `Team Fortress 2/tf` and run `"../bin/captioncompiler" closecaption_<whatever the name is>.txt`

**Comment by Blueberryy** [comment]
thank you i will try

**Comment by Blueberryy** [comment]
> The caption compiler expects to be ran from a folder with gameinfo.txt, and the closecaption file to be in the resource folder.
> 
> Put your txt file into `Team Fortress 2/tf/resource`, then open a command prompt in `Team Fortress 2/tf` and run `"../bin/captioncompiler" closecaption_<whatever the name is>.txt`

It barely works, but doesn't create a file for some reason

**Comment by AwfulRanger** [comment]
If it's not crashing or erroring it should create a .dat file in the resource folder. The text file has to be in UCS-2 little endian format, maybe your text editor saved it in a different format.

Try compiling one of the default unmodified closecaption files, if it doesn't work there's either an issue with your captioncompiler or you're doing something wrong somewhere.

**Comment by Blueberryy** [comment]
ah lol for some reason it created .dat file for **Team Fortress 2\hl2\resource**

**Comment by Blueberryy** [comment]
Also here's another code for batch file `"*insert_your_disc*:\*insert_program_files_folder*\Steam\SteamApps\common\Team Fortress 2\bin\captioncompiler.exe" -game "*insert_your_disc*:/*insert_program_files_folder*/Steam/SteamApps/common/Team Fortress 2/tf/" "*insert_your_disc*:\*insert_program_files_folder*\Steam\SteamApps\common\Team Fortress 2\tf\resource\closecaption_<whatever the name is>.txt"`
It works better for me.

**Comment by gtamike** [comment]
Notepad ++ Convert (Encoding tab) closecaption_english.txt to UTF-16 LE BOM
Drag and Drop closecaption_english.txt
\common\GarrysMod\bin\captioncompiler.exe

In Hammer - To trigger it the resource/closecaption_english.dat

lua_run
local q=string.char(34)for _, ply in pairs(player.GetAll()) do ply:SendLua('RunConsoleCommand('..q..'closecaption'..q..','..q..'1'..q..'); RunConsoleCommand('..q..'cc_emit'..q..','..q..'god.help'..q..')') end

E.G. of custom message (closecaption_english.txt)

lang
{
	Language "English"
	Tokens
	{
		// messages - use UNIQUE names
		"god.help"		"<len:4>God Help! God Help Me!"
	}
}

https://developer.valvesoftware.com/wiki/Closed_Captions
