### ISSUE TITLE
Some texts are not right

### ISSUE THREAD

**Issue by Blueberryy** [AwfulRanger/closecaption_english#2]
I saw some issues like: _Engineer: Sorry, man._ but as wiki says he said _Sorry, ma'am._
https://wiki.teamfortress.com/wiki/Engineer_responses and **Dominating a Pyro** category.

**Comment by AwfulRanger** [comment]
It's hard to tell with some lines. The wiki's transcripts are unofficial as far as I know, so it could be either one.
